#!/bin/sh -x
# See https://docs.docker.com/docker-hub/builds/advanced/
[ "$SOURCE_COMMIT" ] || SOURCE_COMMIT="$(git rev-parse HEAD)"
CREATED="$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
: ${IMAGE_NAME:=$DOCKER_REPO:$DOCKER_TAG}
docker build \
    --build-arg CREATED=$CREATED \
    --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
    -f $DOCKERFILE_PATH -t $IMAGE_NAME .
